FROM public.ecr.aws/lambda/python:3.12

COPY pyproject.toml .
RUN pip install --no-cache-dir .

COPY src ${LAMBDA_TASK_ROOT}/

# le handler : module.fonction
CMD ["ingestion.lambda_handler.handler"]